# operant_conditioning_task プログラムの設定

# 設定フェーズの順番を名前で示したリストです。
phase_list = ["phase1", "phase2", "phase3", "phase4", "phase5_1", "phase5_2", "phase5_3", "phase5_4", "phase5_5", "phase5_6", "phase6"]

# 開始設定フェーズの名前です。
current_phase = "phase2"

# 設定フェーズ phase1 の更新判定の評価に用いる現在の試行からの試行回数です。
num_trials_before = 10

# 設定フェーズ phase1 の更新判定の評価に用いるキューの呈示から lick 行動までの反応時間のクリア値 (sec) です。
response_time_threshold = 10

# 設定フェーズ phase1 の更新判定の評価に用いるキューの呈示から lick 行動までの反応時間をクリアした試行の割合です。
rate_threshold = 0.5

# 設定フェーズ phase 5 と phase 6 の更新判定の評価に用いる試行数のクリア値です。
trial_threshold_list = [100, 200, 300, 400, 500, 600]

# ===== 設定フェーズの設定パラメーター =====
#
# 以下で、各設定フェーズの設定パラメーターを指定します。
# stimulus_duration_in_s: -1 の場合、時間無制限です。
# x: 正解の nose poke ターゲットの番号です。
#   番号リストのリスト形式です。
#   この順番で繰り返し各試行に適用されます。

[phase1]
#x = [[3, 4, 5], [3, 4, 5], [3, 4, 5], [3, 4, 5], [3,4], [3]]
x = [[], [], [], [], [], []] #phase1ではNP hole消灯
is_nose_poke_skip = true
is_lick_wait = false # lick_stateをskipさせないためにはここをtrueにする必要があるが現状の実装ではdelay stateを使うためfalseで良い
delay_state_skip = false
reward_state_skip =1
is_perservative = false
wait_time_in_s = 14
variable_interval_in_s = [8,7,5,2,10,2,6,7,4,5,1,3,1,10,2,3,4,2,6,10,9,6,9,3,1,5,3,9,5,2,2,8,9,1,9,7,3,8,1,8,8,10,5,8,6,3,4,6,4,9,7,2,7,5,4,1,10,5,1,9,7,1,4,4,7,6,10,7,1,2,9,3,10,10,6,8,6,2,4,3,2,3,8,6,10,8,1,6,4,5,9,4,7,3,5,7,9,10,8,5]
timeout_in_s = 0
limited_hold_in_s = 0
stimulus_duration_in_s = 0 #ここは0でいいのか要確認。
num_trials_per_experiment = 99 #最大trialを指定

[phase2]
x = [[1,2, 3], [1,2, 3], [1,2, 3], [1,2, 3], [1,2, 3], [1,2, 3]]
is_nose_poke_skip = false
is_lick_wait = false #lick_stateはskip
delay_state_skip = true
reward_state_skip = 1
is_perservative = false # delay stateでのNPは無関係。
wait_time_in_s = 0
variable_interval_in_s = [2, 3, 3, 5, 1, 4, 5, 4, 1, 2, 5, 4, 1, 5, 5, 3, 4, 2, 2, 4, 1, 2, 1, 5, 4, 1, 3, 2, 3, 1, 2, 5, 1, 4, 1, 3, 2, 3, 5, 1, 4, 5, 1, 5, 3, 5, 3, 2, 3, 4, 4, 1, 2, 2, 1, 1, 3, 5, 1, 1, 0]
timeout_in_s = 0
limited_hold_in_s = 0
stimulus_duration_in_s = 55 #phase2ではこれをtrialの長さにする #ここが-1の場合は、無制限を意味したりする。
num_trials_per_experiment = 59

[phase3]
x = [[3, 4, 5], [3, 4, 5], [3, 4, 5], [3, 4, 5], [4], [3]]
is_nose_poke_skip = false
is_lick_wait = true
delay_state_skip = false
reward_state_skip = false
is_perservative = false
wait_time_in_s = 0
variable_interval_in_s = [0]
timeout_in_s = 0
limited_hold_in_s = 0
stimulus_duration_in_s = -1
num_trials_per_experiment=0

[phase4]
x = [[3, 4, 5], [3, 4, 5], [3, 4, 5], [3, 4, 5], [4], [3]]
is_nose_poke_skip = false
is_lick_wait = true
delay_state_skip = false
reward_state_skip = false
is_perservative = false
wait_time_in_s = 0
variable_interval_in_s = [0]
timeout_in_s = 0
limited_hold_in_s = 0
stimulus_duration_in_s = -1
num_trials_per_experiment=0

[phase5_1]
x = [[3, 4, 5], [3, 4, 5], [3, 4, 5], [3, 4, 5], [4], [3]]
is_nose_poke_skip = false
is_lick_wait = true
delay_state_skip = false
reward_state_skip = false
is_perservative = true
wait_time_in_s = 5
variable_interval_in_s = [0]
timeout_in_s = 5
limited_hold_in_s = 5
stimulus_duration_in_s = 30
num_trials_per_experiment=0

[phase5_2]
x = [[3, 4, 5], [3, 4, 5], [3, 4, 5], [3, 4, 5], [4], [3]]
is_nose_poke_skip = false
is_lick_wait = true
delay_state_skip = false
reward_state_skip = false
is_perservative = true
wait_time_in_s = 5
variable_interval_in_s = [0]
timeout_in_s = 5
limited_hold_in_s = 5
stimulus_duration_in_s = 15
num_trials_per_experiment=0

[phase5_3]
x = [[3, 4, 5], [3, 4, 5], [3, 4, 5], [3, 4, 5], [4], [3]]
is_nose_poke_skip = false
is_lick_wait = true
delay_state_skip = false
reward_state_skip = false
is_perservative = true
wait_time_in_s = 5
variable_interval_in_s = [0]
timeout_in_s = 5
limited_hold_in_s = 5
stimulus_duration_in_s = 10
num_trials_per_experiment=0

[phase5_4]
x = [[3, 4, 5], [3, 4, 5], [3, 4, 5], [3, 4, 5], [4], [3]]
is_nose_poke_skip = false
is_lick_wait = true
delay_state_skip = false
reward_state_skip = false
is_perservative = true
wait_time_in_s = 5
variable_interval_in_s = [0]
timeout_in_s = 5
limited_hold_in_s = 5
stimulus_duration_in_s = 7
num_trials_per_experiment=0

[phase5_5]
x = [[3, 4, 5], [3, 4, 5], [3, 4, 5], [3, 4, 5], [4], [3]]
is_nose_poke_skip = false
is_lick_wait = true
delay_state_skip = false
reward_state_skip = false
is_perservative = true
wait_time_in_s = 5
variable_interval_in_s = [0]
timeout_in_s = 5
limited_hold_in_s = 5
stimulus_duration_in_s = 5
num_trials_per_experiment=0

[phase5_6]
x = [[3, 4, 5], [3, 4, 5], [3, 4, 5], [3, 4, 5], [4], [3]]
is_nose_poke_skip = false
is_lick_wait = true
delay_state_skip = false
reward_state_skip = false
is_perservative = true
wait_time_in_s = 5
variable_interval_in_s = [0]
timeout_in_s = 5
limited_hold_in_s = 5
stimulus_duration_in_s = 3
num_trials_per_experiment=0

[phase6]
x = [[3, 4, 5], [3, 4, 5], [3, 4, 5], [3, 4, 5], [4], [3]]
is_nose_poke_skip = false
is_lick_wait = true
delay_state_skip = false
reward_state_skip = false
is_perservative = true
wait_time_in_s = 5
variable_interval_in_s = [0]
timeout_in_s = 5
limited_hold_in_s = 5
stimulus_duration_in_s = 1
num_trials_per_experiment=0
